### ISSUE TITLE
Validator: tag error is not necessary

### ISSUE THREAD

**Issue by rodionos** [axibase/axibase-charts-vscode#137] opened 2018-09-26 15:55 UTC
```
parent is interpreted as a series tag and is sent to the server. Remove the setting from the [tags] section or enclose it double-quotes to suppress the warning.
```

In this case, `Parent` is correctly defined. Why is classified as a setting here?

```
  list diskAdapters = fcs0, fcs3, fcs4, fcs7
    
  [series]
    display = false
    [tags]
      Disk_Name = *
      Parent = *     

  for da in diskAdapters
  [series]
    label = @{da}
    value = sumTag(series, '@{da}', value)   
  endfor
```

![image](https://user-images.githubusercontent.com/2098022/46092543-c30a1e00-c1bd-11e8-8e20-53c9a6077c73.png)

**Comment by kirmanak** [comment] 2018-09-28 07:54
@rodionos it is a duplicate of #42

**Closed by kirmanak** 2018-09-28 07:54 UTC
