### ISSUE TITLE
Validator: error when checking series requirements

### ISSUE THREAD

**Issue by rodionos** [axibase/axibase-charts-vscode#44] opened 2018-09-17 13:13 UTC
![image](https://user-images.githubusercontent.com/2098022/45625030-96a32300-ba94-11e8-9efc-6aa127f673da.png)

```
[configuration]
  height-units = 5
  width-units = 1
  timespan = 1 day
  script = $('<style>.legend{display:inline} td {padding: 0px; padding-right: 4px; min-width: 11px; line-height: 14px; border-radius: 10px} .ok {background-color: green} .warn {background-color: yellow} .err {background-color: red}</style>').appendTo('head')

  table = abc
  attribute = cde
  
[group]

  [widget]
    type = calendar
    timespan = 8 hour
    summarize-period = 5 minute    

    script
      var stylesheet = document.createElement("style");
      stylesheet.innerHTML = ".axi-calendarchart .axi-chart-series rect:not([fill]):not(.tail) {fill:red}";
      document.head.appendChild(stylesheet);     
    endscript

    [series]
      entity = ent1
```

**Comment by kirmanak** [comment] 2018-09-21 08:09
@rodionos Please, test at the last revision. The issue must be a duplicate of #52 which was fixed in #76

**Closed** 2018-09-21 11:01 UTC
