### ISSUE TITLE
Validator: `mode` setting suggests erroneous options

### ISSUE THREAD

**Issue by kghamilton89** [axibase/axibase-charts-vscode#160] opened 2018-10-02 12:41 UTC
Each widget (`type`) has different possibilities for `mode` setting. Regardless of what my `type` setting is, the same list of `mode` suggestions are presented, `mode = hierarchy` for example does not work when `type = gauge`.

**Comment by rodionos** [comment] 2018-10-02 13:55
Duplicate of #55

**Closed by rodionos** 2018-10-02 13:55 UTC
