### ISSUE TITLE
Validator: check the relationship between thresholds and colors

### ISSUE THREAD

**Issue by rodionos** [axibase/axibase-charts-vscode#141] opened 2018-09-27 17:36 UTC
```
[widget]
    type = gauge
	title = Memory Usage
    thresholds = 0, 60, 80, 100
    colors = green, orange, red, black, red, orange
```

Applies to gauge, calendar, treemap widgets

**Comment by kirmanak** [comment] 2018-09-28 08:45
@rodionos this is a duplicate of #120

**Closed by kirmanak** 2018-09-28 08:45 UTC
