### ISSUE TITLE
Validator: `class` suggestion is erroneous

### ISSUE THREAD

**Issue by kghamilton89** [axibase/axibase-charts-vscode#161] opened 2018-10-02 13:26 UTC
When `type = box`, `mode` setting can only be `metro`. Validator suggests `terminal` (general suggestion, because this is the accepted value for `property-table` widget).

**Comment by rodionos** [comment] 2018-10-02 13:55
Duplicate of #55

**Closed by rodionos** 2018-10-02 13:55 UTC
