### ISSUE TITLE
valid start-time  highlighted as incorrect

### ISSUE THREAD

**Issue by rodionos** [axibase/axibase-charts-vscode#320] opened 2019-05-23 17:46 UTC
These are valid start-time expressions.

```
start-time = current_day + 9 hour + 50 minute
```

```
start-time = current_day + 9 * hour + 50 * minute
```

The error is:

```
start-time should be a date. ...
```

**Comment by annstriganova** [comment] 2019-05-23 18:28
Duplicate of #318

**Closed by annstriganova** 2019-05-23 18:28 UTC
